# Generated by Django 4.2.6 on 2023-11-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like_post',
            constraint=models.UniqueConstraint(fields=('user_id', 'post_id'), name='unique_likes'),
        ),
    ]
